<script>    
        // $(document).ready(function () {
        //     console.log('jQuery loaded for this specific page!');
        //     // Your custom jQuery code here
        //     $(".page-footer").addClass("intro");
        // });

    // function loadJQuery(callback) {
    //     if (typeof window.jQuery === 'undefined') {
    //         var script = document.createElement('script');
    //         script.src = 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.4/jquery.min.js';
    //         script.type = 'text/javascript';
    //         script.onload = function () {
    //             if (typeof callback === 'function') {
    //                 callback(window.jQuery);
    //             }
    //         };
    //         document.head.appendChild(script);
    //     } else {
    //         if (typeof callback === 'function') {
    //             callback(window.jQuery);
    //         }
    //     }
    // }

    // Usage
    // loadJQuery(function ($) {
    //     console.log('jQuery loaded from CDN!');        
    //     $(".page-footer").addClass("introcdn");               
    // });    
</script>